name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Info
        run: |
          pwd
          ls -la
          cargo --version
          rustc --version
      
      - name: Find Cargo.toml
        run: find . -name Cargo.toml
      
      - name: Build
        run: |
          for dir in */; do
            if [ -f "${dir}Cargo.toml" ]; then
              echo "Building in ${dir}"
              cd "${dir}"
              cargo build --verbose
              cd ..
            fi
          done

      - name: Run tests
        run: |
          for dir in */; do
            if [ -f "${dir}Cargo.toml" ]; then
              echo "Testing in ${dir}"
              cd "${dir}"
              cargo test --verbose --lib
              cd ..
            fi
          done

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Run Clippy
        run: |
          for dir in */; do
            if [ -f "${dir}Cargo.toml" ]; then
              echo "Running Clippy in ${dir}"
              cd "${dir}"
              cargo clippy -- -D warnings
              cd ..
            fi
          done

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Rename cargo.toml if exists
        run: |
          if [ -f "cargo.toml" ]; then
            mv cargo.toml Cargo.toml
          fi
      - name: Format
        run: |
          for dir in */; do
            if [ -f "${dir}Cargo.toml" ]; then
              echo "Formatting in ${dir}"
              cd "${dir}"
              cargo fmt --all --check
              cd ..
            fi
          done